const characters = [
    {
        name: "Gumi",
        spriteLink: "Sprites/GumiSprite.png",
        characterImageLink: "Characters/Gumi.png",
        description: "Gumi is a fiery daredevil and scavenger who enjoys hunting for treasure and gambling.",
        species: "Syrian Hamster",
        age: "Young Adult",
        gender: "Female",
        habitat: "Nom's Hollow",
        occupation: "Scavenger",
        personality: "Energetic, hot-tempered, strong-willed, adventurous, and outgoing but also kind and reliable",
        background: "Gumi's burrow was originally in an area that was overrun by beasts and all of her loot and treasured belongings were lost. As a result, she had to find a new place to keep her stash safe, and that’s how she found Nom's Hollow. Along the way, she made some friends and learned to share the 'glory of the loot' with her friends."
    },
    {
        name: "Brody",
        spriteLink: "Sprites/BrodySprite.png",
        characterImageLink: "Characters/Brody.png",
        description: "Brody is a harvester and crop expert.",
        species: "Syrian Hamster",
        age: "Adult",
        gender: "Male",
        habitat: "Nom's Hollow",
        occupation: "Harvester/Farmer",
        personality: "Calm, Generous, Thoughtful, Strong and Helpful",
        background: "Brody had a magnificent farm near Nom's hollow before the undead invaded and his crops were destroyed. He was offered a place at Nom's Hollow and has learned to cultivate a new harvest within the burrows of the hollow. His crops provide enough food to feed everyone at Nom's Hollow."
    },
    {
        name: "Elder Nom",
        spriteLink: "Sprites/NomSprite.png",
        characterImageLink: "Characters/Nom.png",
        description: "Elder Nom is the founder of Nom's Hollow and a protector and guide to all of the hamsters that live there.",
        species: "Long-Haired Syrian Hamster",
        age: "Senior",
        gender: "Male",
        habitat: "Nom's Hollow",
        occupation: "Sage",
        personality: "Wise, Cunning, Mischievous, Gentle",
        background: "Elder Nom founded Nom's Hollow as a safe haven for hamsters to stay in times of need and a place to host events for the community. When the surrounding areas were attacked and overrun with dangerous creatures that forced hamsters from their homes, he kept Nom's Hollow open to any hamsters in need and used an ancient magic to cast a protective shield over the tree."
    },
    {
        name: "Colt",
        spriteLink: "Sprites/ColtSprite.png",
        characterImageLink: "Characters/Colt.png",
        description: "Colt is a stubborn but dedicated leader who maintains the order within Nom's Hollow and offers support where it is needed.",
        species: "Roborovski Dwarf Hamster",
        age: "Adult",
        gender: "Male",
        habitat: "Nom's Hollow",
        occupation: "Commander/Leader",
        personality: "Hot-Headed, Confident, Stubborn, Vigilant, Loyal, Compassionate, Skillful, Intelligent",
        background: "Colt is Elder Nom's best friend and right-hand hamster. He keeps the order within the hollow and always has his eyes out for any trouble. He is reliable and always plans ahead, and looks to help where he can. He originally lived in a small burrow near the hollow and had previously assisted with organizing events at the hollow, but much like many other hamsters, he also lost his home to the madness that overtook the area and fled to Nom's Hollow. He does what he can to keep everyone safe and helps out the other hamsters whenever he can."
    },
    {
        name: "Rio",
        spriteLink: "Sprites/RioSprite.png",
        characterImageLink: "Characters/Rio.png",
        description: "Rio is a fashionable designer and a skilled tailor.",
        species: "Long-Haired Syrian Hamster",
        age: "Young Adult",
        gender: "Male",
        habitat: "Nom's Hollow",
        occupation: "Tailor/Fashion Designer",
        personality: "Sassy, Bold, Witty, Cheerful, Stylish, Creative, Thoughtful, Generous",
        background: "Rio's dream is to become a world-renowned fashion designer and to make the world a more 'fabulous' place. He had a shop in what was once a village, but disease, madness and death drove everyone out and he found his way to Nom's Hollow along with Shay after losing everything but the supplies that he could salvage and carry with him. He has since created his own little 'outlet' within the hollow and creates new designs with whatever new supplies he can get his paws on. He is always on the lookout for new materials, and eager to share his creations with anyone he can. He is also a good friend and most hamsters enjoy his company and sassy opinions, even if they might not be as enthusiastic about fashion as he is."
    },
    {
        name: "Niko",
        spriteLink: "Sprites/NikoSprite.png",
        characterImageLink: "Characters/Niko.png",
        description: "Niko is a gentle healer with a kind heart.",
        species: "Long-Haired Syrian Hamster",
        age: "Young Adult",
        gender: "Female",
        habitat: "Nom's Hollow",
        occupation: "Medic/Healer/Herbologist",
        personality: "Gentle, Compassionate, Thoughtful, Calm, Soft-Spoken, Selfless, Generous",
        background: "Niko is a skilled medic, healer and herbologist. Before the cataclysm erupted, she would volunteer at Nom's Hollow and opened a clinic to help any hamsters in need. Her clinic was destroyed, and she fled to Nom's Hollow where she continued to volunteer her skills. She hates to see any hamster or other creature suffer, and does everything she can to make everyone's day a better one."
    },
    {
        name: "Penny",
        spriteLink: "Sprites/PennySprite.png",
        characterImageLink: "Characters/Penny.png",
        description: "Penny is an unskilled clairvoyant who is plagued with a spiritual onslaught.",
        species: "Russian Dwarf Hamster",
        age: "Young Adult",
        gender: "Female",
        habitat: "Nom's Hollow",
        occupation: "Clairvoyant/Medium",
        personality: "Shy, Quiet, Timid, Troubled, Anxious, Gentle, Caring",
        background: "Penny lost her family to madness and disease, and was found by Colt and Gumi during a scavenging mission. She is plagued with visions of death, and is sensitive to spiritual energy. As a result, she can both communicate with the dead and be manipulated by them. Some of her visions distort into hallucinations and she is unable to control her abilities, which results in difficulty in her ability to discern between what's real and not real. She is fearful and timid, and has a hard time asking for help when she needs it."
    },
    {
        name: "Russell",
        spriteLink: "Sprites/RussellSprite.png",
        characterImageLink: "Characters/Russell.png",
        description: "Russell is the hollow's innkeeper and master chef.",
        species: "Syrian Hamster",
        age: "Adult",
        gender: "Male",
        habitat: "Nom's Hollow",
        occupation: "Innkeeper/Chef",
        personality: "Relaxed, Cool, Attentive, Confident, Supportive, Reliable",
        background: "Russell maintains the inn within the hollow and is also a great chef. He is very personable and a great communicator. Even if his services aren't needed, the other hamsters know that they can count on him and enjoy visiting him for the company and to enjoy his relaxed nature. He has a way of putting everyone's minds at ease, and is a strong shoulder to lean on for anyone in need."
    },
    {
        name: "Shay",
        spriteLink: "Sprites/ShaySprite.png",
        characterImageLink: "Characters/Shay.png",
        description: "Shay is a knowledgeable scribe and recordkeeper.",
        species: "European Hamster",
        age: "Adult",
        gender: "Female",
        habitat: "Nom's Hollow",
        occupation: "Scribe/Recordkeeper",
        personality: "Observant, Intelligent, Kind, Caring, Calm, Supportive",
        background: "Shay was originally a librarian and lived in the same village as Rio. When the village was destroyed, she took as many books, scrolls and records as she could and fled to Nom's Hollow along with Rio. She opened up a new makeshift library within the hollow, but hopes to recover some of the documents that were lost and continue scribing to retain as much knowledge as possible."
    },
    {
        name: "Chai",
        spriteLink: "Sprites/ChaiSprite.png",
        characterImageLink: "Characters/Chai.png",
        description: "Chai is a wanderer and newcomer to Nom's Hollow. Not much is known about her.",
        species: "Syrian Hamster",
        age: "Young Adult",
        gender: "Female",
        habitat: "Nom's Hollow",
        occupation: "Wanderer/Nomad",
        personality: "Silent, Helpful, Observant, Compassionate, Innocent, Clumsy",
        background: "Chai is a bit of a mystery. She doesn’t speak, and is a newcomer to Nom’s Hollow who was discovered by Colt and Brody as they were scouting the area for activity. Much of what is known about her is a guess to those around her, but she can often be found wandering around the hollow and occasionally follows other hamsters around to see if there’s anything she can help with. She is also clumsy, however, and although it seems that she means well, sometimes the other hamsters feel more comfortable doing things on their own."
    },


]